### PR TITLE
official support for Z010D

### PR DESCRIPTION
**Pull request by SakilMondal**

### CODE REVIEW

**Comment by axel-rank** [comment]
Hi, is it possible to make Z00ED be official supported too? Hardware is nearly the same.

**Comment by Kuberrocks96** [comment]
that is Zenfone 2 Laser 5 inch variant, am i right?

**Comment by axel-rank** [comment]
Howto compile? Maybe I can do it. Where can I find docs how to do it?

**Comment by Kuberrocks96** [comment]
@axel-rank Refer to some LineageOS compiling guide, first learn how to compile Lineage OS.
After that make necessary changes on tree to compile DotOS, Z00T, Z00L & Z010D peeps can help you out further. But learn to compile LOS first.

You can join our Telegram community for any feedbacks  t.me/dotos

**Pull request merged**
