### PR TITLE
Gcam via ota (test)

### PR DESCRIPTION
**Pull request by Destiny911gtr**

### CODE REVIEW

**Comment by IacobIonut01** [comment]
@Destiny911gtr lolol, he know me deleted that gcam?

**Comment by ganeshi4u** [comment]
bitch lasagna. CONFLICTS!

**Comment by Destiny911gtr** [comment]
Kek

**Comment by Destiny911gtr** [comment]
Oh, damn i forgot to fix the link, shiiiiit

**Comment by Kuberrocks96** [comment]
@Destiny911gtr Niceee

**Comment by IacobIonut01** [comment]
Create new folder in your device folder named "extras", here u can add any extra files

**Comment by Kuberrocks96** [comment]
@IacobIonut01 Yeah

**Pull request closed without merging**
